languageCode = 'en-us'
title = 'The Curious Leader'
theme = 'coaching'
[params]
  subtitle = 'Big ideas to catalyze your growth'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
          [markup.goldmark.extensions.extras.delete]
            enable = true
          [markup.goldmark.extensions.extras.subscript]
            enable = true